### ISSUE TITLE
[1.12.2] Held Item Tooltips broken?

### ISSUE THREAD

**Issue by SonicX8000** [Fuzss/consolehud#3]
Minecraft: 1.12.2
Forge: 14.23.5.2836

Mods: 1
ConsoleHUD-v1.3-1.12.2

-----

Unless it's just me... I don't see the Tooltip appearing when selecting items. Tried with Enchanted Items, Shulker Boxes, and still... no Tooltip shows.

Going back to 'ConsoleHUD-v1.2-1.12.2'... the Tooltip appears as normal.

**Comment by SonicX8000** [comment]
Issue still occurs in 'ConsoleHUD-v1.3.1-1.12.2'. I also tried updating Forge to '14.23.5.2838' and that didn't seem to do anything.

**Comment by Fuzss** [comment]
Yeah, I feared that might become an issue. What you need to do is to go into your options.txt file and change `heldItemTooltips` to true.

**Comment by Fuzss** [comment]
The reason this happened is that before v1.3 I was deactivating vanilla held item tooltips by changing that option. That wasn't a good thing, because after removing the mod the option might stay deactivated, so exactly what happened in your case. V1.3+ still checks for the heldItemTooltips option which is causing your problem. Will remove the check in the next version.

**Comment by Fuzss** [comment]
A fix was pushed as commit 530e3d1 and can be found as v1.3.2 on Curse.
