### ISSUE TITLE
[Suggestion] More control over held tooltip contents

### ISSUE THREAD

**Issue by IdrisQe** [Fuzss/consolehud#4]
As it stands, the durability display can be turned on/off, and modded content can be denied, as well as per-item changes, etc. with a max number of lines.

I suggest some more configurability to this:
-Enable/Disable enchantments on tooltip [Boolean]
-Max number of lines _for enchantments_ [Integer]
-Modes: [String]
--Enchants listed in order of ID/application "BASIC"
--Enchants listed in order of strength "STRENGTH"

-Enable/Disable potion info on tooltip [Boolean]
-Max number of lines _for potion info_
-Display potion time [Boolean]
-Display potion strength [Boolean]

(and similar things to the above for other such repeatable information)

-String Blacklist: If string is found in tooltip, line does not display on any item.
eg. "Curse of", will omit any tooltip (in this case, likely any vanilla Curse Enchantments) that contains the text "Curse of" [Curse of Binding, etc.]
-Exceptions: List of item IDs that have blacklisted text shown anyway.

-Whitelist: If string is found in tooltip, line displays on the item even if otherwise omitted.
-Exceptions: List of item IDs that have whitelisted text not shown anyway.

**Comment by Fuzss** [comment]
Those are some nice suggestions. Making held item tooltips a lot more configurable was actually the main reason for their rewrite in v1.3. This new system is already in place, but unfortunately it's not accessible by the user since I wasn't able to work on a proper configuration interface so far.
As for hiding curses you might like my [Sneaky Curses](https://minecraft.curseforge.com/projects/sneaky-curses) mod. It'll also affect held item tooltips when "Show Modded Tooltips" is enabled.

**Comment by Fuzss** [comment]
Will get back to this at some point, closing it now though as it is no relevant issue.
