### ISSUE TITLE
[Suggestion] Custom clientside saving icon from local files

### ISSUE THREAD

**Issue by IdrisQe** [Fuzss/consolehud#5]
Basically what it says on the tin. Should someone not like the default saving icon included, it should be possible to swap it out for anything else, bigger, smaller, less intrusive, extremely attention-grabbing, etc. depending on preference and artistic merit of selected image.

**Comment by Fuzss** [comment]
The current implementation isn't necessarily designed for this, but it's definitely possible. You can simply use a resource pack to replace assets > consolehud > textures > gui > auto_save.png.
When the animated icon is enabled in the config (which it is by default) you will have to replace every one of the large chests, even if it's just a static image you want instead. Otherwise you can disable the chest animation in the config, then the small chest icon in the top right will be used or whatever you put there.

**Comment by Fuzss** [comment]
Apart from that I don't really see a necessity in making it easier to change the icon since it's possibly already without major limitations.
